[package]
name = "axle_math"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/Estikno/axle"
license = "Apache-2.0"
rust-version = "1.80.1"

[dependencies]
eyre = "0.6.12"
thiserror = "1.0.63"

[dev-dependencies]
assert_approx_eq = "1.1.0"
