#pragma once

#include "axpch.hpp"

#include "Core/Resource/ResourceManager.hpp"
#include "Renderer/Shaders/Shader.hpp"
#include "Core/Types.hpp"

#include "glm/fwd.hpp"

namespace Axle {
    /**
     * All the functionality of this class is NOT THREAD SAFE and should only be accessed by the render thread.
     * */
    class ShaderManager {
    public:
        ShaderManager() {}
        ~ShaderManager() {}

        ShaderManager(const ShaderManager&) = delete;
        ShaderManager& operator=(const ShaderManager&) = delete;

        /**
         * Initializes everything that is needed for this manager to work properly;
         * */
        static void Init();

        /**
         * Deletes and deallocates all the resources used by the manager.
         * */
        static void Shutdown();

        /**
         * Creates a shader and specifies its source with the filename provided.
         *
         * @param filename The path to the file containing the shader source
         * @param type Type of the shader
         *
         * @returns The shader id generated by OpenGL
         * */
        inline static u32 CreateShader(const std::string& filename, ShaderType type) {
            return s_Instance->CreateShaderImpl(filename, type);
        }

        /**
         * Creates a shader program and links the provided shaders to the program.
         *
         * @param shader1 ID of a shader to attach
         * @param shader2 ID of a shader to attach
         *
         * @returns The program ID generated by OpenGL
         * */
        inline static u32 CreateShaderProgram(u32 shader1, u32 shader2) {
            return s_Instance->CreateShaderProgramImpl(shader1, shader2);
        }

        /**
         * Creates a shader program and links the provided shaders to the program.
         *
         * @param shader1 ID of a shader to attach
         * @param shader2 ID of a shader to attach
         * @param shader3 ID of a shader to attach
         *
         * @returns The program ID generated by OpenGL
         * */
        inline static u32 CreateShaderProgram(u32 shader1, u32 shader2, u32 shader3) {
            return s_Instance->CreateShaderProgramImpl(shader1, shader2, shader3);
        }

        /**
         * Creates a shader program and links the provided shaders to the program.
         *
         * @param shader1 ID of a shader to attach
         * @param shader2 ID of a shader to attach
         * @param shader3 ID of a shader to attach
         * @param shader4 ID of a shader to attach
         *
         * @returns The program ID generated by OpenGL
         * */
        inline static u32 CreateShaderProgram(u32 shader1, u32 shader2, u32 shader3, u32 shader4) {
            return s_Instance->CreateShaderProgramImpl(shader1, shader2, shader3, shader4);
        }

        /**
         * Tells OpenGL to use the provided program
         *
         * @param id ID of the shader program
         * */
        inline static void UseProgram(u32 id) {
            s_Instance->UseProgramImpl(id);
        }

        /**
         * Sets a uniform bool of a specified program
         *
         * @param id ID of the shader program
         * @param name Name of the uniform variable
         * @param value Value to set the uniform to
         * */
        inline static void SetBool(u32 id, const std::string& name, bool value) {
            s_Instance->SetBoolImpl(id, name, value);
        }
        /**
         * Sets a uniform int of a specified program
         *
         * @param id ID of the shader program
         * @param name Name of the uniform variable
         * @param value Value to set the uniform to
         * */
        inline static void SetInt(u32 id, const std::string& name, i32 value) {
            s_Instance->SetIntImpl(id, name, value);
        }
        /**
         * Sets a uniform float of a specified program
         *
         * @param id ID of the shader program
         * @param name Name of the uniform variable
         * @param value Value to set the uniform to
         * */
        inline static void SetFloat(u32 id, const std::string& name, f32 value) {
            s_Instance->SetFloatImpl(id, name, value);
        }
        /**
         * Sets a uniform mat4 of a specified program
         *
         * @param id ID of the shader program
         * @param name Name of the uniform variable
         * @param value Value to set the uniform to
         * */
        inline static void SetMat4(u32 id, const std::string& name, const glm::mat4& value) {
            s_Instance->SetMat4Impl(id, name, value);
        }

        /**
         * Clears all allocated memory
         * */
        inline static void Clear() {
            s_Instance->ClearImpl();
        }

    private:
        // Static methods implementations
        u32 CreateShaderImpl(const std::string& filename, ShaderType type);
        u32 CreateShaderProgramImpl(u32 shader1, u32 shader2);
        u32 CreateShaderProgramImpl(u32 shader1, u32 shader2, u32 shader3);
        u32 CreateShaderProgramImpl(u32 shader1, u32 shader2, u32 shader3, u32 shader4);
        void UseProgramImpl(u32 id);
        void SetBoolImpl(u32 id, const std::string& name, bool value);
        void SetIntImpl(u32 id, const std::string& name, i32 value);
        void SetFloatImpl(u32 id, const std::string& name, f32 value);
        void SetMat4Impl(u32 id, const std::string& name, const glm::mat4& value);
        void ClearImpl();

        /**
         * Checks wether the current linking of shaders was successful or not.
         *
         * @param ID of the program
         * */
        void CheckShaderProgramLinkingErrors(u32 id);

        static std::unique_ptr<ShaderManager> s_Instance;

        std::unordered_map<u32, Shader> m_IDToShader;
        std::unordered_map<Shader, u32> m_ShaderToID;
        std::unordered_map<u32, ResourceManager::ManagedFileHandle> m_IDToFileHandle;

        std::unordered_set<u32> m_ProgramsIDs;
    };
} // namespace Axle
